project 'PolyvVodRnDemo.xcodeproj'

platform :ios, '8.0'
inhibit_all_warnings!

target 'PolyvVodRnDemo' do
  	
  	pod 'XRCarouselView', '~> 2.6.1'
  	pod 'YYWebImage', '~> 1.0.5'
  	pod 'FDStackView', '~> 1.0.1'
  	pod 'Masonry'

	# PLVVodSDK
    pod 'PolyvVodSDK', '~> 2.5.4'
    
    # 使用投屏功能的客户需要集成
    pod 'LBLelinkKit'

	# POLYV Open Source
	pod 'PLVVodDanmu', '~> 0.0.1'
	pod 'PLVSubtitle', '~> 0.1.0'

end
